#!/bin/python
import os
import sys
from pygenix.utils import platform
from pygenix.ani import animatedtext
# from assets.textani import Loader
from assets.utils import Loader
from time import sleep
import shutil
try:
    pkg  = sys.argv[2]
except IndexError:
    pass
from getpass import getuser
user = getuser()
home = f"/home/{user}/zap"
if sys.argv[1] == "-i":
    with Loader("Cloning repo"):
        os.system(f"cd {home}/packages/ && git clone -q --single-branch --branch {pkg} https://github.com/LIGHTNING283/zap-packages.git {pkg} && cd {pkg}")
    os.system("sudo bash install.sh")
    if os.path.isfile(f"{home}/packages/{pkg}/requirements.txt"):
        with Loader("Installing Dependencies"):
            os.chdir(f"{home}/packages/{pkg}/")
            os.system("pip install reqirements.txt")

elif sys.argv[1] == "-r":
    os.system(f"bash {home}/zap/packages/{pkg}/uninstall.sh")
    shutil.rmtree(f"{home}/packages/{pkg}")
    

elif sys.argv[1] == "-u":
        os.system(f"git clone --single-branch --branch pkgs https://github.com/LIGHTNING283/zap.git pkgs && cd pkgs && rm -rf  {home}/zap/pkgs.txt && cp pkgs.txt {home}/zap/")
        print("Package update Done..")